// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBqX4bziBdKmQVza7S23okqbh33eOckw0',
    appId: '1:6615281795:web:34f21d461284ad4a80ebb6',
    messagingSenderId: '6615281795',
    projectId: 'board-assistant',
    authDomain: 'board-assistant.firebaseapp.com',
    storageBucket: 'board-assistant.appspot.com',
    measurementId: 'G-WJY0HQBHCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOPVQlg86XzHjO3qy4-eApBnKIYzE1gu8',
    appId: '1:6615281795:android:f37c0c6b4eb1a56b80ebb6',
    messagingSenderId: '6615281795',
    projectId: 'board-assistant',
    storageBucket: 'board-assistant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwDYIRRwV72iJsqA-_LWPkhjwUAarITWc',
    appId: '1:6615281795:ios:21313d045b3649f880ebb6',
    messagingSenderId: '6615281795',
    projectId: 'board-assistant',
    storageBucket: 'board-assistant.appspot.com',
    iosClientId: '6615281795-1mgu4kq6bafhjeobr8qm38ift8aur4pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.boardAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwDYIRRwV72iJsqA-_LWPkhjwUAarITWc',
    appId: '1:6615281795:ios:21313d045b3649f880ebb6',
    messagingSenderId: '6615281795',
    projectId: 'board-assistant',
    storageBucket: 'board-assistant.appspot.com',
    iosClientId: '6615281795-1mgu4kq6bafhjeobr8qm38ift8aur4pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.boardAssistant',
  );
}
